1. 각 사람의 객관식 점수(True의 갯수 센후*4), 점수 계산, np.dot(a,s) 도트 연산 활용 a는 학생 번호
(0~19 객관식, 20~21행 주관식, 0~9 사람별 답안 셋, 10컬럼 정답)

In [2]:
import numpy as np
score = np.loadtxt('python_score.csv', delimiter=',', dtype='float64')

In [13]:
score

array([[ 3.,  3.,  4.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  3.,  4.,  4.,  2.,  2.,  4.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  2.,  1.,  1.],
       [ 2.,  2.,  3.,  2.,  4.,  2.,  2.,  4.,  4.,  2.,  2.],
       [ 2.,  4.,  2.,  4.,  2.,  2.,  2.,  2.,  4.,  2.,  2.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  2.,  4.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 4.,  3.,  4.,  4.,  2.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 3.,  3.,  3.,  2.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 3.,  2.,  3.,  3.,  3.,  3.,  1.,  3.,  3.,  3.,  3.],
       [ 2.,  2.,  4.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  1.,  1.,  2.,  2

In [14]:
# Right Answer Sheet
ras = score[:20,-1]
ras

array([3., 4., 1., 1., 2., 2., 1., 4., 4., 2., 4., 3., 3., 3., 2., 2., 1.,
       2., 2., 2.])

In [15]:
# Objective Answer Sheet of Students
oas = score[:20,:-1].T
oas

array([[3., 4., 1., 1., 2., 2., 1., 4., 4., 2., 4., 3., 3., 3., 2., 2.,
        1., 2., 2., 2.],
       [3., 4., 1., 1., 2., 4., 1., 4., 4., 2., 3., 3., 3., 2., 2., 2.,
        1., 2., 2., 1.],
       [4., 4., 1., 1., 3., 2., 1., 4., 4., 2., 4., 3., 3., 3., 4., 2.,
        1., 2., 4., 2.],
       [3., 4., 1., 1., 2., 4., 1., 4., 4., 2., 4., 2., 3., 3., 2., 1.,
        1., 2., 2., 4.],
       [3., 4., 1., 1., 4., 2., 1., 4., 4., 2., 2., 3., 3., 3., 2., 1.,
        1., 2., 2., 4.],
       [3., 3., 1., 1., 2., 2., 1., 4., 4., 2., 4., 3., 3., 3., 2., 2.,
        1., 2., 2., 2.],
       [3., 4., 1., 1., 2., 2., 1., 4., 4., 2., 4., 3., 3., 1., 2., 2.,
        1., 2., 2., 3.],
       [3., 4., 1., 1., 4., 2., 1., 4., 4., 2., 4., 3., 3., 3., 2., 2.,
        1., 2., 2., 2.],
       [3., 2., 1., 2., 4., 4., 1., 4., 4., 2., 4., 3., 3., 3., 2., 2.,
        2., 4., 2., 1.],
       [3., 2., 1., 1., 2., 2., 1., 4., 2., 2., 4., 3., 3., 3., 2., 2.,
        1., 2., 2., 3.]])

In [26]:
# 점수 set 만들기(오답 체크)
bool_dset = (oas==ras)
bool_dset

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True],
       [ True,  True,  True,  True,  True, False,  True,  True,  True,
         True, False,  True,  True, False,  True,  True,  True,  True,
         True, False],
       [False,  True,  True,  True, False,  True,  True,  True,  True,
         True,  True,  True,  True,  True, False,  True,  True,  True,
        False,  True],
       [ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True, False,  True,  True,  True, False,  True,  True,
         True, False],
       [ True,  True,  True,  True, False,  True,  True,  True,  True,
         True, False,  True,  True,  True,  True, False,  True,  True,
         True, False],
       [ True, False,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True],
       [ T

In [40]:
# 점수 set 만들기2(bool_dset을 int로 변경)
int_dset = bool_dset.astype(int)
Obj_score = int_dset*4
Obj_score

array([[4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 0, 4, 4, 4, 4, 0, 4, 4, 0, 4, 4, 4, 4, 4, 0],
       [0, 4, 4, 4, 0, 4, 4, 4, 4, 4, 4, 4, 4, 4, 0, 4, 4, 4, 0, 4],
       [4, 4, 4, 4, 4, 0, 4, 4, 4, 4, 4, 0, 4, 4, 4, 0, 4, 4, 4, 0],
       [4, 4, 4, 4, 0, 4, 4, 4, 4, 4, 0, 4, 4, 4, 4, 0, 4, 4, 4, 0],
       [4, 0, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 0, 4, 4, 4, 4, 4, 0],
       [4, 4, 4, 4, 0, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 0, 4, 0, 0, 0, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 0, 0, 4, 0],
       [4, 0, 4, 4, 4, 4, 4, 4, 0, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 0]])

In [67]:
np.sum(Obj_score,1)

array([80, 64, 64, 64, 64, 76, 72, 76, 52, 68])

In [68]:
# Subjective Answer Sheet of Students
subj_score = score[20:,:-1].T
subj_score

array([[ 9.,  5.],
       [ 4.,  7.],
       [10.,  8.],
       [ 9.,  5.],
       [ 6.,  7.],
       [ 8.,  8.],
       [10.,  6.],
       [ 7.,  8.],
       [ 6.,  9.],
       [ 9., 10.]])

In [70]:
np.sum(subj_score,1)

array([14., 11., 18., 14., 13., 16., 16., 15., 15., 19.])

In [71]:
total_score=np.sum(Obj_score,1)+np.sum(subj_score,1)
print (total_score)

[94. 75. 82. 78. 77. 92. 88. 91. 67. 87.]
